Blog/src/blogproject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import (login_view,register_view,logout_view)

urlpatterns = [
    path('admin/', admin.site.urls),
    #--Direct Path - <appname>.views.<function_name>
    path(r'posts/', include("posts.urls"),name="posts"),  #-- Anythings comes as posts/ - redirect it to urls.py of Posts Application
    path(r'api/posts/', include("posts.api.urls"),name="posts-api"),  #-- Anythings comes as api/posts/ - redirect it to urls.py of posts/api Application
    path(r'comments/', include("comments.urls"),name="comments"),  #-- Anythings comes as posts/ - redirect it to urls.py of Posts Application
    path(r'login/', login_view, name="login"),
    path(r'logout/', logout_view, name="logout"),
    path(r'register/', register_view, name="register"),
    path(r'', include("posts.urls"),name="posts"),  #-- Anythings comes as / - redirect it to urls.py of Posts Application
]
#--- The blow configuration is done to serve Static File During Development
#--- It is not a good practice for Production. In production generally files are served from Cloud
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/src/posts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "posts" #--Assigning an App Name ensures we can use the same functions in other apps as well
urlpatterns = [
    #-- URLS only Allows Regular Expressions to be applied and not Paths
    path(r'', views.post_list,name="list"),
    url(r'^create/$', views.post_create),
    # url(r'^detail/(?P<id>\d+)/$', views.post_detail),
    # url(r'^(?P<id>\d+)/$', views.post_detail), #---Only using Key after Post
    # url(r'^(?P<id>\d+)/$', views.post_detail,name = "detail"), #---Only using Key after Post
    url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name='detail'), #---Url Modified to accept Slugs
    # path('<str:slug>/$', views.post_detail,name = "detail"),
    url(r'^(?P<slug>[\w-]+)/update/$', views.post_update,name="update"),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.post_delete),
]

Blog/src/posts/models.py
from pyexpat import model
import re
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
#--Take Some Action Right Before Model is getting saved
from django.utils.text import slugify
from django.conf import settings
from django.utils import timezone
from markdown_deux import markdown
from django.utils.safestring import mark_safe
from comments.models import Comment
from django.contrib.contenttypes.models import ContentType
from .utils import get_read_time



#Model Manager Examples :
# Post.objects.all() , Post.create(user=user,title=title,......)

#--We can override the ModelManagers with our custom function
#--Overriding the Default all
class PostManager(models.Manager):
    def active(self,*args,**kwargs):
        return super(PostManager,self).filter(draft=False).filter(publish__lte=timezone.now())

#--Upload images to a specific location inside Media URL
def upload_location(instance,filename):
    print("Instance :: " ,instance)
    return f"images/{filename}"
    
# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,default=1,on_delete=models.CASCADE) #---Creating a relationship between Post and User # default=1 means superuser
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,null=True,blank=True,width_field="width_field",height_field="height_field") #---Need Pillow Library to Use This Field
    height_field = models.IntegerField(default=0) #--Autodetermines Height of Image
    width_field = models.IntegerField(default=0) #--Autodetermines Width of Image
    content = models.TextField()
    draft = models.BooleanField(default=False) #--For Drafts
    publish = models.DateTimeField(default = None,auto_now=False,auto_now_add=False)  #--For Drafts
    read_time = models.TimeField(null=True,blank=True)  #--For Storing ReadTime
    updated = models.DateTimeField(auto_now=True,auto_now_add=False) 
    timestamp = models.DateTimeField(auto_now=False,auto_now_add=True) 

    objects = PostManager()

    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug":self.slug})
    
    def get_markdown(self): #--This method will return markdown/truncated content to display in the post list
        return mark_safe(markdown(self.content))

    #-- This Property of the instance can be used anywhere
    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance,new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug = slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = f"{slug}-{instance.id}"
        return create_slug(instance,new_slug=new_slug)
    return slug

#-- Whatever actions which we need to perform before saving a model needs to be done here
def pre_save_post_reciever(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    #---- Save ReadTime

    if instance.content:
        html_string = instance.get_markdown()
        read_time = get_read_time(html_string)
        instance.read_time = read_time
    


#--- Pre Save will run before everytime a model is getting saved
pre_save.connect(pre_save_post_reciever,sender = Post)

Blog/src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' >

        <title>{% block head_title %} Django Blog Project {% endblock head_title %}</title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}"/> <!-- Reusable incase your Static URL Changes -->
    {% block head_extra %} {% endblock head_extra %}
    </head>
    <body>
        <div id="fb-root"></div>
        <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v12.0" nonce="EcZl7jYs"></script>
        {% include "messages_display.html" %}

        <div class="container">
            <ol class="breadcrumb">
                <li><a href='{% url "posts:list" %}'>Home</a></li>
                <li><a href='{% url "posts:list" %}'>Posts</a></li>
                {% block post_detail_link %}
                {% endblock %}
                {% if not request.user.is_authenticated %}
                <li class="pull-right"><a href='{% url "register" %}'>Register</a></li>
                <li class="pull-right"><a href='{% url "login" %}'>Login</a></li>
                {% else %}
                <li class="pull-right"><a href='{% url "logout" %}'>Logout</a></li>
                {% endif %}
            </ol>
        {% block content %}
        {% endblock content %}
        </div>
        <!--For Rendering Markdown Components-->
        <!-- Latest compiled and minified JavaScript -->
        <script   src="http://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   crossorigin="anonymous"></script>

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

        <script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'></script>

        <script type="text/javascript">
            $(document).ready(function(){
                $(".content-markdown").each(function(){
                var content =  $(this).text()
                console.log(content)
                var markedContent = marked(content)
                console.log(markedContent)
                $(this).html(markedContent)
                })

                console.log("Here")
                $(".comment-reply-btn").click(function(event){
                    event.preventDefault();
                    $(this).parent().next(".comment-reply").fadeToggle();
                })
                
                $(".content-markdown img").each(function(){
                 $(this).addClass("img-responsive")
                })
                
                var titleInput = $("#id_title");
                function setTitle(value){
                    $("#preview-title").text(value)
                }
                setTitle(titleInput.val())
                titleInput.keyup(function(){
                    var newTitle = $(this).val()
                    setTitle(newTitle)
                })

                var contentInput = $("#wmd-input-id_content");
                function setContent(value){
                    var markedContent = marked(value)
                    $("#preview-content").html(markedContent)
                    $("#preview-content img").each(function(){
                        $(this).addClass("img-responsive")
                    })
                }
                setContent(contentInput.val())
                contentInput.keyup(function(){
                    var newContent = $(this).val()
                    setContent(newContent)
                })
                

            })
        </script>
    </body>
</html>

<!-- To Generate Facebook Like/Share/Comments -->
<!-- https://developers.facebook.com/docs/plugins/like-button -->

Blog/src/templates/comment_thread.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load urlfy %} <!-- Loading Custom Template -->
{% block head_title %} {{instance.title}} | {{block.super}}{% endblock head_title %}
{% block content %}
{{ object }}
<div class="col-sm-8 col-sm-offset-2">
        <blockquote>
                <p>{{comment.content}}</p>
                <footer>via {{ comment.user }} on {{comment.timestamp }} | {% if comment.children.count > 0 %} {{ comment.children.count}} Replies  {% endif %} {% if request.user == comment.user %} <a href="{{ comment.get_delete_url }}">  Delete  </a>{% endif %}</footer>
                <hr/>
                <div>
                        <!-- Rendering Replies -->
                        {% for child_comment in comment.children %}
                                <blockquote>
                                        <p>{{child_comment.content}}</p>
                                        <footer>via {{ child_comment.user }} on {{child_comment.timestamp }} | {% if request.user == child_comment.user %}<a href="{{ child_comment.get_delete_url }}"> Delete </a>{% endif %}</footer>
                                </blockquote>
                        {% endfor %}
                        {% if request.user.is_authenticated %}
                        <form method="POST" action="."> {% csrf_token %}
                                {{ comment_form | crispy }}
                                <input type="hidden" name="parent_id" value='{{ comment.id }}'> <!--- ID Of the Parent Comment Against whom we will Post Reply -->
                                <input type="submit" value="Reply" class="btn btn-default">
                        </form>
                        {% else %}
                        <p> You must login to comment</p>
                        {% endif %}
                </div>
        </blockquote>
        <hr/>
</div>
{% endblock content %}

Blog/src/templates/confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load urlfy %} <!-- Loading Custom Template -->
{% block head_title %} {{instance.title}} | {{block.super}}{% endblock head_title %}
{% block content %}
{{ object }}
<div class="col-sm-8 col-sm-offset-2">

    <form method="POST" action="."> {% csrf_token %}
            <p> Are you sure you want to delete : "{{ object.content }}" ?</p> 
            <input type="submit" value="Confirm" class="btn btn-warning">
            <a href='{{ object.get_absolute_url }}' class="btn btn-default">Cancel</a>
    </form>

</div>
{% endblock content %}

Blog/src/templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-sm-6 col-sm-offset-3">
<h1>{{ title }}</h1>

<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form | crispy}}
    </table>
    <input type="submit" class="btn btn-default" value="{{ title }}">
</form>
</div>
{% endblock content %}

Blog/src/templates/messages_display.html
<div class="messages">
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
</div>

Blog/src/templates/post_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}
{% block content %}
<div class="col-sm-6">
<h1>Preview</h1>
<div class="content-preview">
    <h3 id = "preview-title"></h3>
    <p id="preview-content"></p>
</div>
</div>
<!--- {{block.super}} Will Fetch the Parent Class Content-->
<!--- Action : Where to send the Form Next After Submit-->
<div class="col-sm-6">
<h1>Form</h1>
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form | crispy}}
    </table>
    <input type="submit" class="btn btn-default" value="Create Post">
</form>
</div>
{% endblock content %}

Blog/src/templates/post_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load urlfy %} <!-- Loading Custom Template -->
{% block head_title %} {{instance.title}} | {{block.super}}{% endblock head_title %}
{% block post_detail_link %}
<li><a href = '{{ instance.get_absolute_url }}'>{{ instance.title }}</a></li>
{% endblock %}
{% block content %}
        <div class="col-sm-8 col-sm-offset-2">
        <h1>{{title}} <small>{%if instance.draft %} <span style="color:red">Draft </span>{% endif %}{{instance.publish}}</small></h1>
        <p> Read Time : {{ instance.read_time | time:"i" }} Seconds</p>
        {% if instance.image %}
        <img src="{{ instance.image.url }}" class="img-responsive"> 
        {% endif %}
        {% if instance.user.get_full_name %}
                <p> Author : {{instance.user.get_full_name}} </p>
        {% else %}
                <p> Author : {{instance.user}} </p>
        {% endif %}
        <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-width="" data-layout="button" data-action="like" data-size="small" data-share="true"></div>        
        <hr>
        <!-- <a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">Share on Facebook</a>
        <a href='https://plus.google.com/share?url={{request.build_absolute_uri}}'>Share on Google+</a>
        <a href="https://twitter.com/home?status={{instance.content | urlify}}%20{{request.build_absolute_uri}}">Share on Twitter</a>
        <a href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}&title={{instance.title}}&summary={{share_string}}&source={{request.build_absolute_uri}}">Share on Linkedin</a>
        <a href="http://www.reddit.com/submit?url={{request.build_absolute_uri}}&title={{instance.title}}">Share on Reddit</a> -->
        <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
        <div class=" content-markdown"> {{instance.content }}</br> </div>
        <div>
                <p class="lead">Comments</p>
                {% if request.user.is_authenticated %}
                <form method="POST" action="."> {% csrf_token %}
                        {{ comment_form | crispy }}
                        <input type="submit" value="Post Comment" class="btn btn-default">
                </form>
                {% else %}
                 <p> You must login to comment</p>
                {% endif %}
                <hr/>
                {% for comment in comments %}
                <blockquote>
                        <p>{{comment.content}}</p>
                        <footer>via {{ comment.user }} on {{comment.timestamp }} | {% if comment.children.count > 0 %} {{ comment.children.count}} Comments | {% endif %}<a class="comment-reply-btn" href="#">Reply</a> | <a class="" href="{{comment.get_absolute_url}}">Thread</a></footer>
                        <div class="comment-reply">
                                <!-- Rendering Replies -->
                                {% for child_comment in comment.children %}
                                        <blockquote>
                                                <p>{{child_comment.content}}</p>
                                                <footer>via {{ child_comment.user }} on {{child_comment.timestamp }}</footer>
                                        </blockquote>
                                {% endfor %}
                                {% if request.user.is_authenticated %}
                                <form method="POST" action="."> {% csrf_token %}
                                        {{ comment_form | crispy }}
                                        <input type="hidden" name="parent_id" value='{{ comment.id }}'> <!--- ID Of the Parent Comment Against whom we will Post Reply -->
                                        <input type="submit" value="Reply" class="btn btn-default">
                                </form>
                                {% else %}
                                <p> You must login to comment</p>
                                {% endif %}
                        </div>
                </blockquote>
                <hr/>
                {% endfor %}
        </div>

        <!-- Uncomment the following to allow Facebook Comments -->
        <!-- <div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-width="" data-numposts="5"></div> --> 
        </div>
        </div>
        </div>
{% endblock content %}

Blog/src/templates/post_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="col-sm-6 col-sm-offset-3">
<h1>{{title}}</h1>
<form method="GET" action="">
    <div class="input-group">
        <input class="form-control" type="text" name = "q" placeholder="Search Posts" value="{{ request.GET.q}}"/>
        <span class="input-group-btn">
        <input class="btn btn-default" type="submit" value="Search">
        </span>
    </div>
</form>
    {% for obj in page_obj %}
    <div class="row">
        <div class="col-sm-12">
            <div class="thumbnail">
                {% if obj.image %}
                <img src="{{ obj.image.url }}" class="img-responsive"> 
                {% endif %}
                <div class="caption">
                    <!-- <img src="..." alt="..."> -->
                    <!-- <a href = "/posts/{{obj.id}}">{{obj.title}}</a></br> -->
                    <!-- <h3><a href = "{% url 'posts:detail' slug=obj.slug %}">{{obj.title}}</a> <small> {{obj.timestamp|timesince}}</small></h3> -->
                    {% if obj.draft %} <h3 style="color:red"> Draft {% if obj.publish > today %} Future Post {% endif %}</h3> {% endif %}
                    <h3><a href = "{{ obj.get_absolute_url }}">{{obj.title}}</a> <small> {{obj.publish |timesince}}</small></h3>
                    <p class="content-markdown">{{obj.content}}</p>
                    <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
                    <p>{% if obj.user.get_full_name %}
                        <p> Author : {{obj.user.get_full_name}} </p>
                        {% else %}
                        <p> Author : {{obj.user}} </p>
                        {% endif %}</p>
                </div>
            </div>
        </div>
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>

{% endblock content %}